apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: agenda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb # Changé le nom du Deployment
  namespace: agenda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb # Changé le label selector
  template:
    metadata:
      labels:
        app: mariadb # Changé le label du Pod
    spec:
      containers:
      - name: mariadb # Changé le nom du conteneur
        image: mariadb:latest # CHANGEMENT: Utilisation de l'image MariaDB
        env:
        # Configuration Root (pour la gestion interne de la BDD)
        - name: MYSQL_ROOT_PASSWORD
          value: "supersecure"
        # Configuration du Super-Utilisateur de l'Application
        - name: MYSQL_DATABASE
          value: "agenda"
        - name: MYSQL_USER # CHANGEMENT: Ajout du nom d'utilisateur
          value: "user"
        - name: MYSQL_PASSWORD 
          value: "md_pass"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-storage # Renommé pour plus de clarté
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage # Renommé
        persistentVolumeClaim:
          claimName: mariadb-pvc # Le nom du PVC mis à jour
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service # Changé le nom du Service
  namespace: agenda
spec:
  selector:
    app: mariadb # CHANGEMENT: Le sélecteur cible le nouveau Pod (app: mariadb)
  ports:
  - port: 3306
    targetPort: 3306